### ISSUE TITLE
Is there any class or function to generate timeout_timestamp ?

### ISSUE THREAD

**Issue by Widiskel** [initia-labs/initia.js#59]
Help
<img width="437" alt="Screenshot 2024-06-07 at 01 12 21" src="https://github.com/initia-labs/initia.js/assets/97203329/2f91b861-294e-4480-91c6-669b8f637e5f">

i try to use MsgTransfer but im stuck on timeout_timestamp
with error code

```bash
rpc error: code = Unknown desc = failed to execute message; message index: 0: invalid packet timeout: current timestamp: 1717697454292389880, timeout timestamp 171900000010000000: timeout elapsed [cosmos/ibc-go/v8@v8.2.0/modules/core/04-channel/types/timeout.go:35] with gas used: '365625': unknown request
```

Is there any class or function to generate timeout_timestamp ?
if it self generated, is there a pattern to generate it ?

i provide example of timestamp on explorer
<img width="464" alt="Screenshot 2024-06-07 at 01 16 50" src="https://github.com/initia-labs/initia.js/assets/97203329/5aec52e1-eea4-4714-80fa-8be333a374b4">

**Comment by ALPAC-4** [comment]
Hi sorry for the late response. The timeout timestamp is a unit of nanoseconds. So for example if you want to set timeout timestamp to 10mins from now, you can set timestamp like this `(new Date().valueOf() + 1000 * 60 * 10) * 1000000`

**Comment by Widiskel** [comment]
ahh, i see thanks for the response
